version: '3.8'

services:
  mongo-votacaodbDOCKER:
    image: mongo:7
    container_name: mongo-votacaodbDocker
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: votacaodbDocker
    ports:
      - "27017:27017"
    volumes:
      - mongo_ho_data:/data/db
      - ./init-mongo-ho.js:/docker-entrypoint-initdb.d/init-mongo-ho.js:ro
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-votacaodbDev:
    image: mongo:7
    container_name: mongo-votacaodbDev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: votacaodbDev
    ports:
      - "27018:27017"
    volumes:
      - mongo_dev_data:/data/db
      - ./init-mongo-dev.js:/docker-entrypoint-initdb.d/init-mongo-dev.js:ro
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: unless-stopped
    environment:
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9094
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9093,CONTROLLER://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CLUSTER_ID=mk2xz3H1TAqnqzasCuHCzw
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - app-network
    healthcheck:
      test: kafka-topics.sh --bootstrap-server localhost:9092 --list
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  validador:
    build:
      context: ./validador
      dockerfile: Dockerfile
    container_name: validador
    restart: unless-stopped
    ports:
      - "26000:26000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:26000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ms-votacao-pauta:
    build:
      context: ./ms-votacao-pauta
      dockerfile: Dockerfile
    container_name: ms-votacao-pauta
    restart: unless-stopped
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - KAFKA_SERVERS=kafka:9092
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "30000:30000"
    depends_on:
      mongo-votacaodbDOCKER:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
      validador:
        condition: service_started
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:30000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  app-network:
    driver: bridge

volumes:
  mongo_ho_data:
  mongo_dev_data:
  kafka_data:
  redis_data: