version: '3.8'

services:
  mongo-votacaodbHO:
    image: mongo:7
    container_name: mongo-votacaodbHO
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: votacaodbHO
    ports:
      - "27017:27017"
    volumes:
      - ./init-mongo-ho.js:/docker-entrypoint-initdb.d/init-mongo-ho.js:ro
    networks:
      - app-network

  mongo-votacaodbDev:
    image: mongo:7
    container_name: mongo-votacaodbDev
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: votacaodbDev
    ports:
      - "27018:27017"
    volumes:
      - ./init-mongo-dev.js:/docker-entrypoint-initdb.d/init-mongo-dev.js:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
